export const repos: {id: number, name: string, image: string, title: string, subtitle: string, link: string}[] = [
    {
        id: 1,
        name: 'Wolfgang',
        image: '/repos/wolfgang.jpg',
        title: 'Electronic Application Builder (React + Tailwind)',
        subtitle: 'Our state of the art SPA + Material-UI with a drizzle of our secret sauce.',
        link: 'https://gitlab.com/reframe-financial/frontend/wolfgang',
    },
    {
        id: 1,
        name: 'Sophia',
        image: '/repos/sophia.jpg',
        title: 'Customer Facing Application (Next Js + Tailwind)',
        subtitle: 'Next Js and Tailwind, what a combination for building fast web applications.',
        link: 'https://gitlab.com/reframe-financial/frontend/sofia',
    },
    {
        id: 1,
        name: 'Elizabeth',
        image: '/repos/elizabeth.jpg',
        title: 'Shared libraries (Node Js)',
        subtitle: 'Hosted on top of Gitlab Package Registry, Elizabeth holds the common libraries used by Ingrid, Sally and Marilyn.',
        link: 'https://gitlab.com/reframe-financial/services/elizabeth',
    },
    {
        id: 1,
        name: 'Agnes',
        image: '/repos/agnes.jpg',
        title: 'Apollo GraphQL Gateway',
        subtitle: 'Lot of magic happens behind the scenes. This is like a buffet, you can eat as much as you want but we recommend to grab just what you need.',
        link: 'https://gitlab.com/reframe-financial/services/agnes',
    },
    {
        id: 1,
        name: 'Ingrid',
        image: '/repos/ingrid.jpg',
        title: 'Electronic Application Builder (NodeJs REST API with Dapr)',
        subtitle: 'The underworld starts from here. Microservices, DAPR side-cards, Postgress and more.',
        link: 'https://gitlab.com/reframe-financial/services/ingrid',
    },
    {
        id: 1,
        name: 'Sally',
        image: '/repos/sally.jpg',
        title: 'Rule Engine (NodeJS REST API with Dapr)',
        subtitle: 'Sally drives the flow for an Electronic Application, interacts directly with Ingrid and Marilyn. Also collects telemetry data coming from the user while interacts with the application.',
        link: 'https://gitlab.com/reframe-financial/services/sally',
    },
    {
        id: 1,
        name: 'Marilyn',
        image: '/repos/marilyn.webp',
        title: 'Electronic Application Runner (NodeJS REST API with Dapr)',
        subtitle: 'This is the starting point for an Applicant looking for coverage. A set of questions will be presented to the user, answers will be sent back us not only for persistence also to execute smart decisions connecting with thrid party and machine learning services.',
        link: 'https://gitlab.com/reframe-financial/services/marilyn',
    },
]